I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 119, in script
    python:
ScriptError: could not find label 'world_map'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-7.2.1-sdk/renpy/bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-7.2.1-sdk/renpy/main.py", line 524, in main
    run(restart)
  File "/Applications/renpy-7.2.1-sdk/renpy/main.py", line 139, in run
    renpy.execution.run_context(True)
  File "/Applications/renpy-7.2.1-sdk/renpy/execution.py", line 892, in run_context
    context.run()
  File "game/script.rpy", line 119, in script
    python:
  File "/Applications/renpy-7.2.1-sdk/renpy/script.py", line 886, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'world_map'.

Darwin-18.5.0-x86_64-i386-64bit
Ren'Py 7.2.1.457
renpyTest 1.0
Sat Jun 15 22:01:30 2019
